stages:
 - build
 - deploy

stak-stage-mp-ap-api:
 stage: deploy
 script:
  - cd /home/ubuntu/staking-iac/ansible
  - sudo su ubuntu -c "ansible-playbook stak-stage-mp-ap-api.yml --extra-vars=\"node_git_version=${CI_COMMIT_TAG}\""
 only:
  - /^.*-rc$/
 except:
  - branches
 tags:
  - stak-stage-mp-bastion

prod-stak-mp-ap-api:
 stage: deploy
 variables:
  _ENV: "prod"
  GIT_STRATEGY: none
 script:
  - cd /home/ubuntu/staking-iac/ansible
  # Ensure gitlab.blockchainlabs.asia allow https ssh from runner ip
  # Ensure staking-iac have ssh remote
  # Ensure id_rsa chmod 400
  # Ensure say yes for the first ssh conn
  - sudo su ubuntu -c "export GIT_SSH_COMMAND='ssh -i /home/ubuntu/staking-iac/ansible/id_rsa';git pull ssh terraform"
  - ansible_file=`grep ${CI_PROJECT_NAME}.git *.yml | awk '{print $1}'|awk -F':' '{print $1}' | grep ${_ENV}`
  - sudo su ubuntu -c "ansible-playbook $ansible_file --extra-vars=\"node_git_version=${CI_COMMIT_TAG}\""
 only:
  - /^.*[0-9]$/
 except:
  - branches
 tags:
  - prod-stak-mp-ansible
