stages:
 - build
 - test
 - deploy

variables:
 GIT_STRATEGY: none
 ANSIBLE_DIR: "/home/ubuntu/staking-iac/ansible"
 GIT_DIR: "/home/ubuntu/staking-iac/"
 
.BuildJSApp:
 stage: build
 script:
  #Check out newest source
  - cd ${GIT_DIR}
  - sudo su ubuntu -c "export GIT_SSH_COMMAND='ssh -i /home/ubuntu/staking-iac/ansible/id_rsa';git checkout -f remotes/origin/terraform"
  #Run playbook
  - cd ${ANSIBLE_DIR}
  - ansible_file=`grep ${CI_PROJECT_NAME}.git *.yml | awk '{print $1}'|awk -F':' '{print $1}' | grep ${_ENV}`
  - sudo su ubuntu -c "ansible-playbook $ansible_file --extra-vars=\"${CI_COMMIT_TAG}\""
  
.OnlyStagingMS:
 only:
  - /^.*-ms-rc$/
 except:
  - branches

.OnlyStagingBS:
 only:
  - /^.*-bs-rc$/
 except:
  - branches

.OnlyProductionMS:
 only:
  - /^.*-ms$/
 except:
  - branches

.OnlyProductionBS:
 only:
  - /^.*-bs$/
 except:
  - branches

DeployBinaryStar:
 variables:
  _ENV: "stage" 
 extends:
  - .BuildJSApp
  - .OnlyStagingBS
 tags:
  - stage-stak-mp-ansible
  
DeployMoonStake:
 variables:
  _ENV: "stage" 
 extends:
  - .BuildJSApp
  - .OnlyStagingMS
 tags:
  - stage-stak-mp-ansible

  
